version: '3'

services:

  mysql:
    build: .docker/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: password
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    expose:
      - "13306"
    ports:
      - "13306:3306"

  rundeck:
    build: .docker/rundeck
    depends_on:
      - mysql
    platform: linux/x86_64
    environment:
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: password
      RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
    volumes:
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
    ports:
      - "4440:4440"
